name: "Pull Request Notification"

permissions:
  id-token: write # required to use OIDC authentication
  contents: write # required to checkout the code from the repo
  pull-requests: write # required to comment on the PR
  
on:
  pull_request:
    types:
      - closed

env:
  S3_BUCKET: "docs-krmpesan-app"
  AWS_ROLE: arn:aws:iam::057675665881:role/serverless

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: ap-southeast-1
      - name: Check S3 Bucket If Exist or Not
        uses: tuler/s3-check-action@master
        id: check
        env:
          FILE: "index.html"
          AWS_S3_BUCKET: "${{ env.S3_BUCKET }}-pr-${{ github.event.pull_request.number }}"
      - name: Delete All Files in AWS S3 Bucket
        if: steps.check.outputs.exists == 'true'
        run: |
          aws s3 rm s3://"${{ env.S3_BUCKET }}-pr-${{ github.event.pull_request.number }}" --recursive
      - name: Delete AWS S3 Bucket
        if: steps.check.outputs.exists == 'true'
        run: |
          aws s3 rb s3://"${{ env.S3_BUCKET }}-pr-${{ github.event.pull_request.number }}" --force
      - uses: actions/github-script@v5
        if: steps.check.outputs.exists == 'true'
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hi @${{ github.event.pull_request.user.login }},\n\nYour Pull Request has been successfully deleted from http://${{ env.S3_BUCKET }}-pr-${{ github.event.pull_request.number }}.s3-website-${{ env.AWS_REGION }}.amazonaws.com'
            })
